#created on: Sep 7, 2011
package einstein.riddle

#list any import classes here.



#declare any global variables here

rule "Brit House Red"
    salience 10000

    when
        $person : Person (nationality == Nationality.BRIT && houseColor != HouseColor.RED)
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
        
end

rule "Swede Pet Dog"
    salience 9900

    when
        $person : Person (nationality == Nationality.SWEDE && pet != Pet.DOG)
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
        
end

rule "Dane Drink Tea"
    salience 9800

    when
        $person : Person (nationality == Nationality.DANE && drink != Drink.TEA)
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
        
end

rule "House Green Drink Coffee"
    salience 9700

    when
        $person : Person (houseColor == HouseColor.GREEN && drink != Drink.COFFEE)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end

rule "Smoke PallMall Pet Bird"
    salience 9600

    when
        $person : Person (smoke == Smoke.PALLMALL && pet != Pet.BIRD)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end

rule "House Yellow Smoke Dunhill"
    salience 9500

    when
        $person : Person (houseColor == HouseColor.YELLOW && smoke != Smoke.DUNHILL)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end

rule "House 3 Drink Milk"
    salience 9400

    when
        $person : Person (housePosition == 3 && drink != Drink.MILK)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end

rule "Norwegian House 1"
    salience 9300

    when
        $person : Person (nationality == Nationality.NORWEGIAN && housePosition != 1)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end

rule "Smoke BlueMaster Drink Beer"
    salience 9200

    when
        $person : Person (smoke == Smoke.BLUEMASTER && drink != Drink.BEER)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end

rule "German Smoke Prince"
    salience 9100

    when
        $person : Person (nationality == Nationality.GERMAN && smoke != Smoke.PRINCE)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end

rule "Norwegian lives next to the Blue house"
    salience 9000

    when
        $person : Person (housePosition == 2 && houseColor != HouseColor.BLUE)
        
    then
        //System.out.println("Retracting: " + $person);
        retract($person);
end



